project:
  type: website
  output-dir: docs  

website:
  title: "myblog"
  navbar:
    right:
      - text: "About"
        href: about.qmd

blog:
  type: blog
  authors: ["Claire Saunders"]
  theme: cosmo

site-url: "https://clr-saunders.github.io/myblog/"




